# Configuration options can be accessed as
# configatron.site_name

development: &local
    site_name: SKYS Database
    site_namemobile: BaseApp2 Mobile
    site_url: localhost:3004
    
    company_name: BaseApp2 Ltd
    admin_email: admin@baseapp2.local
    
    support_name: BaseApp2 Support
    support_email: support@baseapp2.local
    
    site_envnote: Local Server

production:
    site_name: BaseApp2
    site_namemobile: BaseApp2 Mobile
    site_url: www.baseapp2.com
    
    company_name: BaseApp2 Ltd
    admin_email: admin@baseapp2.com
    
    support_name: BaseApp2 Support
    support_email: support@baseapp2.com
    
    site_envnote: Production Server
  
staging:
  <<: *local

test:
  <<: *local
